server:
   port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    nonSecurePort: 8888

management:
  security:
     enabled: false
     
spring:
  application:
    name: configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yagodeoz/configuraciones
  profiles:
    active: dev