server:
   port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    nonSecurePort: 8080

spring:
  application:
     name: backend
  cloud:
     config:
       #Si queremos realizar el descubrimiento de servicios
       discovery:
         service-id: CONFIGURATION
         enabled: true
       fail-fast: true